stages:
  - build
  - deploy

variables:
  IMAGE: "<your-docker-username>/my-nginx-app"
  KUBE_CONTEXT: "your-cluster-context"

before_script:
  - echo "Logging in to DockerHub"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

# Build stage
build:
  stage: build
  script:
    - docker build -t $IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE:$CI_COMMIT_REF_NAME

# Deploy stage
deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes using Helm"
    - helm upgrade --install my-nginx ./helm/my-nginx --set image.tag=$CI_COMMIT_REF_NAME
  only:
    - main
